### ISSUE TITLE
one note has issues starting and code is not highlighting.

### ISSUE THREAD

**Issue by legolasdimir** [elvirbrk/NoteHighlight2016#15] opened 2017-08-14 19:40 UTC
I am running office 32-bit and after I install the add-in and start one note I have code I want to highlight. so I highlight the code then click HTML from the tab. it opens the box the first time and the text in one note remains unchanged. I will admit that maybe I didn't understand the instructions but it seemed pretty straight forward. Also, if I close one note and try to restart it, I get the error: one note is cleaning up from the last time it ran and then an error that says one note is having trouble starting then I have to restart my computer to get one note to work again. (UPDATE) it seems that this behavior only happens if you click the language and then hit ok without actually putting any code in the box

**Comment by elvirbrk** [comment] 2017-08-25 11:31
Thanks for feedback, I'll check it out.
When you select code and click on HTML button, then selected text should show-up in new box when it pops out. So when you click OK, your text on OneNote page will be replaced with formatted text.

As for OneNote closing issue, sometimes OneNote process remains in background, so you can find it in Task Manager and kill it.

**Comment by Clintoxen** [comment] 2017-10-12 06:58
Im actually having this issue on the x64 version. Highlighted or copy and paste and nothing happens using the python tab. Close the app and restart iit get the same error as him. Kill the process try it all over again and get the same issue @elvirbrk

**Comment by elvirbrk** [comment] 2017-10-13 14:19
Please try new version v3.1.
I added some error handling so hopefully it will give us some additional info.

**Comment by Clintoxen** [comment] 2017-10-13 17:35
@elvirbrk  
![image](https://user-images.githubusercontent.com/20504430/31558557-5b689d80-b01b-11e7-8048-47807b9e5f77.png)
Error i got

**Comment by Clintoxen** [comment] 2017-10-17 23:20
Another one i got 

![image](https://user-images.githubusercontent.com/20504430/31694089-497a13f8-b370-11e7-8ad1-7b50bc3d6d37.png)

@elvirbrk

**Comment by Clintoxen** [comment] 2017-10-18 04:18
I figured out how to fix it

**Comment by elvirbrk** [comment] 2017-10-19 07:13
Great :)
Can you share how you fixed it in case other encounter similar issue?

**Comment by Clintoxen** [comment] 2017-10-22 19:06
@elvirbrk 

It comes down to some weirdness with how onenote handles copy and pasting and page colors. Its really just a work around since it really is Onenote causing the issue. 

If you use any new versions of Onenote that lets you change the page color, like the windows store version it will cause issues when you are using OneNote 2016. 

If you change the color on a page with notes already on it they color gets copied into the notehighlighter add on and causes the first exception above.  Copying a page with color background and text will weirdly cause one note to see that text as a picture and not text. 

Work around it to create a new blank page and use something like a clipboard manager or notepad to strip all the extra fluff onenote adds to the text. From there you post it in the new page and the add-on will work as expected. Or just completely avoid any and all ways to change page colors etc in onenote.

**Comment by elvirbrk** [comment] 2017-10-24 08:36
Thanks for detailed explanation, I'll make some tests with page color and see if addin can ignore that.

**Comment by Clintoxen** [comment] 2017-11-03 16:23
Ill try it again soon and repo and get back to you

**Closed** 2018-02-08 14:52 UTC
Labels: waiting for feedback

**Comment by ClintOxx** [comment] 2018-07-16 17:07
@elvirbrk sorry for the late reply. It seems like it was an issue caused by having an extra space on the same line before or after the code snippet I was trying to convert with NoteHighlight.
